#cloud-config

#apt_sources:
#    - source: "ppa:fenics-packages/fenics"

package_update: true
package_upgrade: true

packages:
    - git
    - python-pip
    - rabbitmq-server
#    - fenics
#    - gmsh
    - python-numpy
    - python-matplotlib

runcmd:
    - pip install Flask
    - pip install celery
    - pip install flower
    - pip install pickledb
    - pip install simplejson
    - git clone https://github.com/vallemagnusson/messaging.git
    - mv messaging home/ubuntu/messaging
    - git clone https://github.com/vallemagnusson/naca_airfoil.git
    - mv naca_airfoil home/ubuntu/naca_airfoil
    - chmod -R 777 /home/ubuntu/messaging
    - chmod -R 777 /home/ubuntu/naca_airfoil
    - mkdir /home/ubuntu/naca_airfoil/pictures
    - rabbitmqctl add_user mava orkarinte
    - rabbitmqctl add_vhost app2
    - rabbitmqctl set_permissions -p app2 mava ".*" ".*" ".*"
    - cd /home/ubuntu/naca_airfoil
    - sudo -H -u ubuntu bash -c "celery flower -A proj &"
    - sudo -H -u ubuntu bash -c "python flaskApp.py &" 