#cloud-config

apt_sources:
    - source: "ppa:fenics-packages/fenics"

package_update: true
package_upgrade: true

packages:
    - git
    - python-pip
    - fenics
    - python-numpy

runcmd:
    - pip install celery
    - git clone https://github.com/vallemagnusson/messaging.git
    - mv messaging home/ubuntu/messaging
    - git clone https://github.com/vallemagnusson/naca_airfoil.git
    - mv naca_airfoil home/ubuntu/naca_airfoil
    - chmod -R 777 /home/ubuntu/messaging
    - chmod -R 777 /home/ubuntu/naca_airfoil
    - cd /home/ubuntu/naca_airfoil
    - sudo -H -u ubuntu bash -c "celery worker -A proj &"
